baseURL = "https://blog.mikesahari.com/"
languageCode = "en-us"
title = "Didactic Musings"

[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 4

[params]
  author = "Mike Sahari"
  description = "A tech blog for Go, Tech, and all the other things I find interesting."
  menu_item_separator = " - "
  avatar = "images/avatar.jpg"
  favicon = "images/gopher_favicon.svg"

  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/mike-sahari"

  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/catpaladin"

  [[params.social]]
    icon = "brand-mastodon"
    name = "Mastodon"
    url = "https://mastodon.social/@ineedmorecoffee"

  [[params.social]]
    icon = "brand-bluesky"
    name = "Bluesky"
    url = "https://bsky.app/profile/msahari.bsky.social"

  [params.style]
    darkestColor = "#253031"
    darkColor = "#263238"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    primaryColor = "#00B0FF"

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[security]
  enableInlineShortcodes = true

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 80
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10
